source 'https://rubygems.org'

gem 'colorize'
gem 'metadata-json-lint'
gem 'parallel_tests'
gem 'pry'
gem 'puppet', '< 5'
gem 'puppet-strings'
gem 'puppetlabs_spec_helper', '< 3.0.0'
gem 'rspec-puppet-facts'
gem 'rubocop'
gem 'rubocop-rspec'
